/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workoutappv1;

/**
 *
 * @author jdvan
 */
public class RandomSelectPanel extends javax.swing.JPanel {

    /**
     * Creates new form RandomSelectPanel
     */
    public RandomSelectPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noWeightBox = new javax.swing.JCheckBox();
        weightBox = new javax.swing.JCheckBox();
        TRXBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        intensitySlider = new javax.swing.JSlider();
        sliderValue = new javax.swing.JLabel();
        goLabel = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        medicineBallBox = new javax.swing.JCheckBox();
        ballBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        exerciseSlider = new javax.swing.JSlider();
        exerciseValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));
        setPreferredSize(new java.awt.Dimension(500, 500));

        noWeightBox.setText("No Weight");
        noWeightBox.setMaximumSize(new java.awt.Dimension(85, 50));
        noWeightBox.setMinimumSize(new java.awt.Dimension(85, 35));
        noWeightBox.setPreferredSize(new java.awt.Dimension(85, 50));

        weightBox.setText("Weight");
        weightBox.setMaximumSize(new java.awt.Dimension(85, 50));
        weightBox.setMinimumSize(new java.awt.Dimension(85, 35));
        weightBox.setPreferredSize(new java.awt.Dimension(85, 50));
        weightBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightBoxActionPerformed(evt);
            }
        });

        TRXBox.setText("TRX");
        TRXBox.setMaximumSize(new java.awt.Dimension(85, 50));
        TRXBox.setMinimumSize(new java.awt.Dimension(85, 35));
        TRXBox.setPreferredSize(new java.awt.Dimension(85, 50));
        TRXBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRXBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>Select the categories you want, how many different </br>exercises, intensity, then hit GO!!");

        intensitySlider.setMaximum(10);
        intensitySlider.setMinimum(1);
        intensitySlider.setValue(1);
        intensitySlider.setMaximumSize(new java.awt.Dimension(200, 36));
        intensitySlider.setMinimumSize(new java.awt.Dimension(200, 21));
        intensitySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                intensitySliderStateChanged(evt);
            }
        });

        sliderValue.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        sliderValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sliderValue.setText("1");

        goLabel.setBackground(new java.awt.Color(0, 0, 0));
        goLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        goLabel.setForeground(new java.awt.Color(255, 255, 255));
        goLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goLabel.setText("GO!!");
        goLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 102, 102)));
        goLabel.setOpaque(true);

        backLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setText("Back");

        medicineBallBox.setText("Medicine Ball");
        medicineBallBox.setMaximumSize(new java.awt.Dimension(85, 50));
        medicineBallBox.setMinimumSize(new java.awt.Dimension(85, 35));
        medicineBallBox.setPreferredSize(new java.awt.Dimension(85, 50));

        ballBox.setText("Ball");
        ballBox.setMaximumSize(new java.awt.Dimension(85, 50));
        ballBox.setMinimumSize(new java.awt.Dimension(85, 35));
        ballBox.setPreferredSize(new java.awt.Dimension(85, 50));
        ballBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Intensity");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Exercises");

        exerciseSlider.setMaximum(6);
        exerciseSlider.setMinimum(3);
        exerciseSlider.setValue(3);
        exerciseSlider.setMaximumSize(new java.awt.Dimension(200, 31));
        exerciseSlider.setMinimumSize(new java.awt.Dimension(200, 21));
        exerciseSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                exerciseSliderStateChanged(evt);
            }
        });

        exerciseValue.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        exerciseValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exerciseValue.setText("3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noWeightBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ballBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TRXBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(medicineBallBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(weightBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(intensitySlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(exerciseSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(7, 7, 7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(84, 84, 84))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(85, 85, 85)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sliderValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exerciseValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(backLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(330, 330, 330)
                        .addComponent(goLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(intensitySlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(163, 163, 163))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(exerciseSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sliderValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(83, 83, 83)
                                        .addComponent(exerciseValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(46, 46, 46))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(noWeightBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weightBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TRXBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medicineBallBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ballBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(goLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(backLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(121, 121, 121))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TRXBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRXBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TRXBoxActionPerformed

    private void intensitySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_intensitySliderStateChanged
        sliderValue.setText(Integer.toString(intensitySlider.getValue()));
    }//GEN-LAST:event_intensitySliderStateChanged

    private void exerciseSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_exerciseSliderStateChanged
        exerciseValue.setText(Integer.toString(exerciseSlider.getValue()));
    }//GEN-LAST:event_exerciseSliderStateChanged

    private void ballBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ballBoxActionPerformed

    private void weightBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox TRXBox;
    public javax.swing.JLabel backLabel;
    public javax.swing.JCheckBox ballBox;
    public javax.swing.JSlider exerciseSlider;
    private javax.swing.JLabel exerciseValue;
    public javax.swing.JLabel goLabel;
    public javax.swing.JSlider intensitySlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JCheckBox medicineBallBox;
    public javax.swing.JCheckBox noWeightBox;
    public javax.swing.JLabel sliderValue;
    public javax.swing.JCheckBox weightBox;
    // End of variables declaration//GEN-END:variables
}
