/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workoutappv1;

import javax.swing.JLabel;

/**
 *
 * @author jdvan
 */
public class SelectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form SelectionPanel
     */
    public SelectionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        PremadeLabel = new javax.swing.JLabel();
        RandomLabel = new javax.swing.JLabel();

        jSplitPane1.setBackground(new java.awt.Color(0, 0, 0));
        jSplitPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setName("SelectionSPane"); // NOI18N

        PremadeLabel.setBackground(new java.awt.Color(233, 150, 122));
        PremadeLabel.setFont(new java.awt.Font("Comic Sans MS", 2, 20)); // NOI18N
        PremadeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PremadeLabel.setText("<html>Pre-Made<br>Workout</html>");
        PremadeLabel.setOpaque(true);
        PremadeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PremadeLabelMouseClicked(evt);
            }
        });
        jSplitPane1.setRightComponent(PremadeLabel);

        RandomLabel.setBackground(new java.awt.Color(255, 160, 122));
        RandomLabel.setFont(new java.awt.Font("Comic Sans MS", 2, 20)); // NOI18N
        RandomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RandomLabel.setText("<html>Random<br>Workout</html>");
        RandomLabel.setOpaque(true);
        RandomLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RandomLabelMouseClicked(evt);
            }
        });
        jSplitPane1.setLeftComponent(RandomLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RandomLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RandomLabelMouseClicked

    }//GEN-LAST:event_RandomLabelMouseClicked

    private void PremadeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PremadeLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PremadeLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel PremadeLabel;
    public javax.swing.JLabel RandomLabel;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
