/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workoutappv1;

/**
 *
 * @author jdvan
 */
public class WorkoutCountdownPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkoutCountdownPanel
     */
    public WorkoutCountdownPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fiveFourThreeTwoOne = new javax.swing.JLabel();

        fiveFourThreeTwoOne.setBackground(new java.awt.Color(255, 153, 153));
        fiveFourThreeTwoOne.setFont(new java.awt.Font("Comic Sans MS", 0, 200)); // NOI18N
        fiveFourThreeTwoOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fiveFourThreeTwoOne.setText("5");
        fiveFourThreeTwoOne.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fiveFourThreeTwoOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fiveFourThreeTwoOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel fiveFourThreeTwoOne;
    // End of variables declaration//GEN-END:variables
}
