/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workoutappv1;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author jdvan
 */
public class WorkoutSummaryPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkoutSummaryPanel
     */
    public WorkoutSummaryPanel() {
        initComponents();
        workoutSummaryTable.setTableHeader(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        workoutSummaryTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 65)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Summary");

        workoutSummaryTable.setBackground(new java.awt.Color(255, 153, 153));
        workoutSummaryTable.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        workoutSummaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Workout", "Number of Reps", "Time per Rep"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Workout", "Number of Reps", "Time per Rep"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workoutSummaryTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        workoutSummaryTable.setAutoscrolls(false);
        workoutSummaryTable.setGridColor(new java.awt.Color(255, 153, 153));
        workoutSummaryTable.setOpaque(false);
        workoutSummaryTable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        workoutSummaryTable.setSelectionForeground(new java.awt.Color(255, 153, 153));
        jScrollPane2.setViewportView(workoutSummaryTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable workoutSummaryTable;
    // End of variables declaration//GEN-END:variables
}
